//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Clinicas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicasBdEntities : DbContext
    {
        public ClinicasBdEntities()
            : base("name=ClinicasBdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clinicas> clinicas { get; set; }
        public virtual DbSet<consultas> consultas { get; set; }
        public virtual DbSet<detalles_consulta> detalles_consulta { get; set; }
        public virtual DbSet<detalles_receta> detalles_receta { get; set; }
        public virtual DbSet<empleados> empleados { get; set; }
        public virtual DbSet<especialidades> especialidades { get; set; }
        public virtual DbSet<medicamentos> medicamentos { get; set; }
        public virtual DbSet<medicos> medicos { get; set; }
        public virtual DbSet<pacientes> pacientes { get; set; }
        public virtual DbSet<padecimientos> padecimientos { get; set; }
        public virtual DbSet<recetas> recetas { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
