//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Clinicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicamentos
    {
        public int idMedicamentos { get; set; }
        public string nombre { get; set; }
        public string productora { get; set; }
        public string presentacion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string descripcion { get; set; }
    }
}
