//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Areas.Clinicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recetas()
        {
            this.detalles_receta = new HashSet<detalles_receta>();
        }
    
        public int idRecetas { get; set; }
        public int idConsulta { get; set; }
        public string observaciones { get; set; }
    
        public virtual consultas consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalles_receta> detalles_receta { get; set; }
    }
}
